DOMAIN = "ha_mortgage_rates"
PLATFORMS = ["sensor"]

CONF_PROPERTY_VALUE = "property_value"
CONF_MORTGAGE_AMOUNT = "mortgage_amount"
CONF_PURPOSE = "purpose"
CONF_TERM = "term"

PURPOSE_REMORTGAGE = "remortgage"
PURPOSE_FTB = "first_time_buyer"
PURPOSE_HOME_MOVER = "home_mover"
PURPOSE_BTL = "buy_to_let"

PURPOSES = [PURPOSE_REMORTGAGE, PURPOSE_FTB, PURPOSE_HOME_MOVER, PURPOSE_BTL]

DEFAULT_TERM = 25
DEFAULT_PROPERTY_VALUE = 200000
DEFAULT_MORTGAGE_AMOUNT = 150000

UPDATE_INTERVAL_SECONDS = 86400  # 24 hours
REQUEST_TIMEOUT_SECONDS = 30
